### ISSUE TITLE
Some questions about roadmap and making contributions

### ISSUE THREAD

**Issue by pplam** [m-novikov/tree-sitter-sql#19]
Hi @m-novikov , I recently had the need to parse SQL and finally found your project. It's an awesome project and is under active development. I would like to make some contribution to this project but I have a few questions for you

1. Regarding the scope and extent of support for SQL syntax, do you have a roadmap or goal?
2. Will you accept PRs contributed to this project?

Looking forward for your response, thank you!

**Comment by m-novikov** [comment]
Regarding roadmap I am focusing on PostgreSQL compatible syntax. Ideally first milestone would be full support of commonly encountered statements (`SELECT`, `INSERT`, `UPDATE`, `DELETE`) to allow embedding syntax highlighting to other languages.
After this I want to take a closer look at supporting pl/sql and function definitions.

Note that tree-sitter mostly focuses on parsing for editors so there is less strictness in terms of correctness of parsing. Which means there maybe be constructions that will be parsed successfully that aren't necessarily correct syntax in terms of database.

Yes, I'll most definitely accept contributions. Feel free to submit PR or outline the idea so I can get better grasp on your use cases.

**Comment by pplam** [comment]
Understood that, actually I want a parser that can process PostgreSQL and MySQL (and ideally more dialects) compatible grammars. 
Consider that the PostgreSQL dialect is largely SQL standard compliant, if the basic syntax of PostgreSQL is supported, then most corresponding MySQL syntax is covered.

For MySQL specified features, is it possible if we add supporting for them? 
And in long term, do you have a plan to make the SQL parser more general to make it compliant with more dialect?

The next step, I think the supporting of PL/SQL and function definitions will be a great feature.

**Comment by pplam** [comment]
For the less strictness in correctness of parsing, it is ok for me. I want the maximum of successful parsing and the minimum of parse errors.
And for me, the more SQL syntax covered by the grammar defined in `grammar.js`, the better.

**Comment by m-novikov** [comment]
Appreciate it :)
It's better to create fork and submit a PR, it's sadly not possible for me to monitor and grant access to this repo due to security concerns.
